apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-neoflask
  namespace: flaskapp-dev
  labels:
    app: dp-neoflask
  annotations:
    kubernetes.io/change-cause: version 1.16.0
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: neoflask
  template:
    metadata:
      labels:
        app: neoflask
    spec:
      containers:
      - name: neoflask
        image: iamokjin/neoflask:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask
  name: flaskapp
  namespace: flaskapp-dev
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: neoflask
  type: LoadBalancer
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis
  namespace: flaskapp-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: barteks/redis:latest
        ports:
        - name: redisport
          containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: flaskapp-dev
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redisport
  selector:
    app: redis
